version: '3.6'
services:
  hiring:
    container_name: hiring
    image: webdevops/php-apache-dev:7.2
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment: ['WEB_DOCUMENT_ROOT=/var/www', 'WEB_DOCUMENT_INDEX=/var/www/index.php', 'PHP_IDE_CONFIG=serverName=hiring', 'PHP_DEBUGGER=xdebug', 'XDEBUG_REMOTE_AUTOSTART=1', 'XDEBUG_REMOTE_ENABLE=1', 'XDEBUG_REMOTE_CONNECT_BACK=0', 'XDEBUG_REMOTE_HOST=192.168.1.108', 'XDEBUG_REMOTE_PORT=9000', 'XDEBUG_IDEKEY=PHPSTORM', 'PM_MAX_REQUESTS=500']
    networks:
      - default
    ports:
      - '8085:80'
#    labels:
#      - traefik.http.routers.hiring.rule=Host(`hiring.app.com`)
#      - traefik.docker.network=summit
#      - traefik.enable=true
#      - traefik.port=80
#      - traefik.default.protocol=http

  db:
    container_name: db
    image: library/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "pass"
    ports:
      - '3307:3306'
    networks:
      - default

#networks:
#  summit:
#    external: true